"""ac_rowsums_table.py -- the supplement's table of A_C row-sum ranges for every released extraction,
inclusive and proton-tagged, FHC/RHC/combined, from data_release/A_C_<family>_<config>_<obs>.tsv
(2026-09-26; the table had been maintained by hand). Writes tables/ac_rowsums_all.tex and prints the
rows whose sum is negative.
    python3 report/tools/ac_rowsums_table.py
"""
import os
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__)); REP = os.path.dirname(HERE); REL = os.path.join(REP, 'data_release')
CF = ('FHC5', 'RHCFULL', 'COMB')
INCL = [('pmu', r'$p_\mu$'), ('ppi3bin', r'$p_\pi$ (three regions)'), ('costhmu', r'$\cos\theta_\mu$'),
        ('costhpi', r'$\cos\theta_\pi$'), ('thmupi', r'$\theta_{\mu\pi}$')]
P1 = [('pmu', r'$p_\mu$'), ('ppi2bin', r'$p_\pi$ (two regions)'), ('costhmu', r'$\cos\theta_\mu$'),
      ('costhpi', r'$\cos\theta_\pi$'), ('thmupi', r'$\theta_{\mu\pi}$'), ('pp', r'$p_p$'),
      ('Wpipr', r'$W_{\pi p}$'), ('Whad', r'$W_{\rm had}$'), ('dpt2bin', r'$\delta p_T$'),
      ('dphit3bin', r'$\delta\phi_T$'), ('dalphat2bin', r'$\delta\alpha_T$'), ('pn2bin', r'$p_n$')]


def acmat(fam, cfg, obs):
    rows = [l.split() for l in open(os.path.join(REL, f'A_C_{fam}_{cfg}_{obs}.tsv')) if l.strip() and not l.startswith('#')]
    return np.array([[float(x) for x in r[1:]] for r in rows[1:]])


def cell(x):
    return f'${x:.2f}$'.replace('$-0.00$', '$0.00$')


L = [r'% generated by report/tools/ac_rowsums_table.py -- do not edit', r'\begin{center}', r'\small',
     r'\captionof{table}{Range of the $A_C$ row sums of every released extraction, from the result files.}',
     r'\label{tab:ac_rowsums_all}', r'\begin{tabular}{lccc}', r'\toprule', r'Observable & FHC & RHC & combined \\',
     r'\midrule', r'\multicolumn{4}{l}{\emph{Inclusive}}\\', r'\midrule']
neg = []
for fam, obs_l in (('incl', INCL), ('1p', P1)):
    if fam == '1p':
        L += [r'\midrule', r'\multicolumn{4}{l}{\emph{Proton-tagged}}\\', r'\midrule']
    for o, lab in obs_l:
        cells = []
        for c in CF:
            A = acmat(fam, c, o); rs = A.sum(axis=1)
            cells.append(f'{cell(rs.min())}--{cell(rs.max())}')
            for i in np.flatnonzero(rs < 0):
                neg.append((fam, c, o, i + 1, rs[i], A[i, i], rs[i] - A[i, i]))
        L.append(f'{lab} & ' + ' & '.join(cells) + r' \\')
L += [r'\bottomrule', r'\end{tabular}', r'\end{center}']
open(os.path.join(REP, 'tables', 'ac_rowsums_all.tex'), 'w').write('\n'.join(L) + '\n')
print('wrote tables/ac_rowsums_all.tex')
for n in neg:
    print('negative row: %s %s %s bin %d  row sum %.3f  diagonal %.3f  off-diagonal %.3f' % n)
