"""binning_table.py -- the bin-edge table of the analysis note (tab:binning), generated from the release: the
low/high columns of data_release/curves_<family>_FHC5_<obs>.tsv, and for the proton-angle study extractions
(theta_p, theta_pip, outside the release index) the axis of their closure sidecars. Written 2026-09-26 when
the binnings of the 0.50 migration criterion were adopted; the table had been maintained by hand.
Writes tables/binning.tex (analysis note) and tables/binning_1p.tex (proton-tagged note).
    python3 report/tools/binning_table.py
"""
import os, math
HERE = os.path.dirname(os.path.abspath(__file__)); REP = os.path.dirname(HERE)
REL = os.path.join(REP, 'data_release'); PROC = '/data/uboone/processed'
INCL = [('pmu', r'$p_\mu$ (GeV/$c$)', True), ('ppi3bin', r'$p_\pi$ (GeV/$c$)', True), ('costhmu', r'$\cos\theta_\mu$', False),
        ('costhpi', r'$\cos\theta_\pi$', False), ('thmupi', r'$\theta_{\mu\pi}$ (rad)', False)]
P1 = [('pmu', r'$p_\mu$ (GeV/$c$)', True), ('ppi2bin', r'$p_\pi$ (GeV/$c$)', True), ('costhmu', r'$\cos\theta_\mu$', False),
      ('costhpi', r'$\cos\theta_\pi$', False), ('thmupi', r'$\theta_{\mu\pi}$ (rad)', False),
      ('Wpipr', r'$W_{\pi p}$ (GeV/$c^2$)', True), ('Whad', r'$W_{\rm had}$ (GeV/$c^2$)', True),
      ('dpt2bin', r'$\delta p_T$ (GeV/$c$)', True), ('dphit3bin', r'$\delta\phi_T$ (deg)', False),
      ('dalphat2bin', r'$\delta\alpha_T$ (deg)', False), ('pn2bin', r'$p_n$ (GeV/$c$)', True),
      ('pp', r'$p_p$ (GeV/$c$)', True)]
STUDY = [('thetap', r'$\theta_p$ (rad)$^{\dagger}$'), ('thpipr', r'$\theta_{\pi p}$ (rad)$^{\dagger}$')]


def fmt(x):
    if abs(x - math.pi) < 2e-3: return r'$\pi$'
    return f'{round(x, 3):g}'


def curve_edges(fam, obs):
    rows = [l.split('\t') for l in open(os.path.join(REL, f'curves_{fam}_FHC5_{obs}.tsv')) if l[:1].isdigit()]
    return [float(rows[0][1])] + [float(r[2]) for r in rows]


def sidecar_edges(obs):
    import uproot
    return list(uproot.open(f'{PROC}/closure_hists_xsec_ccpi1p_FHC5_{obs}.root')['h_unfolded_nuwro'].axis().edges())


def line(lab, e, open_top):
    txt = ', '.join(fmt(x) for x in e[:-1]) + ', ' + (fmt(e[-1]) + r'$^{*}$' if open_top else fmt(e[-1]))
    return f'      {lab} & {len(e) - 1} & {txt} \\\\'


def table(label, caption, rows, notes):
    return ([r'% generated by report/tools/binning_table.py -- do not edit',
             r'\begin{table}[H]', r'  \centering', caption, rf'  \label{{{label}}}', r'  \small',
             r'  \begin{tabular}{L{3.2cm} c p{8.3cm}}', r'    \toprule', r'    Observable & Bins & Edges \\', r'    \midrule']
            + rows + [r'    \bottomrule', r'  \end{tabular}', r'  \par\smallskip\noindent{\footnotesize ' + notes + '}', r'\end{table}'])


OPEN = (r'$^{*}$ Numerical plotting boundary only: the upper truth bin is open-ended, and a density drawn over the'
        r' conventional width represents the bin integral.')
# 2026-09-27: one table per note (the analysis note carries no proton-tagged material)
L = table('tab:binning',
          r'  \caption{Bin edges of every observable, from the result files. The binnings meet the $0.50$ migration'
          r' criterion (\suppref{Sec.}{sec:binreview}) and are the same in the three configurations.}',
          [line(lab, curve_edges('incl', o), op) for o, lab, op in INCL], OPEN)
open(os.path.join(REP, 'tables', 'binning.tex'), 'w').write('\n'.join(L) + '\n')
L = table('tab:pt_binning',
          r'  \caption{Bin edges of the proton-tagged observables, from the result files. The binnings meet the $0.50$'
          r' migration criterion (\suppref{Sec.}{sec:binreview}) and are the same in the three configurations.}',
          [line(lab, curve_edges('1p', o), op) for o, lab, op in P1] + [line(lab, sidecar_edges(o), False) for o, lab in STUDY],
          r'$^{\dagger}$ Proposed secondary scope (\S\ref{sec:wtki_ang}).\par ' + OPEN)
open(os.path.join(REP, 'tables', 'binning_1p.tex'), 'w').write('\n'.join(L) + '\n')
print('wrote tables/binning.tex and tables/binning_1p.tex')
