"""ensemble_tables_1p.py -- evaluate the three proton-tagged fake-data ensembles (FHC W_had in two
regions, 2026-09-26; FHC two-bin delta p_T and combined two-bin p_n, 2026-09-24/25; 100 members each,
slurm_ensemble_1p.sbatch) with ensemble_stat_pulls.evaluate, write data_release/ensemble_1p_2026-09-26.tsv and the coverage
table of the proton-tagged note, tables/ensemble_1p.tex, which also lists the ensembles of the proton angles
and of theta_p x delta p_T (prerequisite V1) from data_release/ensemble_v1_2026-09-28.tsv (ensemble_tables_v1.py,
run that first). Run slurm/ens_statcov.sh 1p_<cfg> <obs> first so every member has its DataStats table.

    python3 report/tools/ensemble_tables_1p.py
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
from ensemble_stat_pulls import evaluate
R = os.path.abspath(os.path.join(HERE, '..')) + '/'
TAGS = [('1p_fhc5_Whad', r'$d\sigma/dW_{\rm had}$ (two regions), FHC'),
        ('1p_fhc5_dpt2bin', r'$d\sigma/d\delta p_T$ (two bins), FHC'),
        ('1p_comb_pn2bin', r'$d\sigma/dp_n$ (two bins), combined')]
res = {}
for tag, _ in TAGS:
    try: res[tag] = evaluate(tag, 100, quiet=True)
    except Exception as e: print(tag, 'failed:', e)

with open(R + 'data_release/ensemble_1p_2026-09-26.tsv', 'w') as o:
    o.write('# Proton-tagged fake-data ensembles (corrected FHC Run-1 exposure): Poisson throws of the central-value\n'
            '# prediction of the w/ trees (slurm_ensemble_1p.sbatch), each carried through univmake + UnfolderNuMI; pulls against\n'
            '# the fixed central-value truth smeared by each member\'s own A_C. Statistical reference = DataStats covariance of the\n'
            '# member; full = total covariance. Offsets are of the ensemble-mean integral from the reference integral.\n')
    o.write('extraction\tmembers\tbins\tpull_mean_stat\tpull_width_stat\tcov68_stat\tcov95_stat\tpull_mean_full\tpull_width_full'
            '\tcov68_full\tcov95_full\tmean_integral\treference_integral\toffset_pct\toffset_sigma_of_mean\tthrow_to_throw_sd_pct\n')
    for tag, _ in TAGS:
        if tag not in res: continue
        r = res[tag]; s = r['statistical only']; f = r['full']
        o.write(f"{tag}\t{r['members']}\t{r['bins']}\t{s['mean']:.2f}\t{s['width']:.2f}\t{100*s['cov68']:.1f}\t{100*s['cov95']:.1f}"
                f"\t{f['mean']:.2f}\t{f['width']:.2f}\t{100*f['cov68']:.1f}\t{100*f['cov95']:.1f}\t{r['mean_integral']:.4f}"
                f"\t{r['reference_integral']:.4f}\t{r['offset_pct']:.2f}\t{r['offset_sigma']:.1f}\t{r['sd_pct']:.1f}\n")
print('wrote data_release/ensemble_1p_2026-09-26.tsv')

def sg(v, d=2):
    t = f"{v:+.{d}f}"; return t[1:] if float(t) == 0 else t      # no signed zero


def rowvals(r):
    """table cells of one extraction from an evaluate() result or a row of a release TSV"""
    if 'statistical only' in r:
        s, f = r['statistical only'], r['full']
        return (s['mean'], s['width'], 100 * s['cov68'], 100 * s['cov95'], f['width'], r['offset_pct'], r['offset_sigma'],
                r['sd_pct'], r['members'])
    return (float(r['pull_mean_stat']), float(r['pull_width_stat']), float(r['cov68_stat']), float(r['cov95_stat']),
            float(r['pull_width_full']), float(r['offset_pct']), float(r['offset_sigma_of_mean']),
            float(r['throw_to_throw_sd_pct']), int(r['members']))


def row(lab, cfg, r):
    m, w, c68, c95, wf, off, offs, sd, n = rowvals(r)
    return (f"    {lab} & {cfg} & ${sg(m)}$ & ${w:.2f}$ & ${c68:.0f}\\%$ & ${c95:.0f}\\%$ & ${wf:.2f}$ & "
            f"${sg(off, 1)}\\%$ (${sg(offs, 1)}$) & ${sd:.1f}\\%$ \\\\")


# the ensembles of the results proposed on 2026-09-27 (prerequisite V1), from ensemble_tables_v1.py
V1 = R + 'data_release/ensemble_v1_2026-09-28.tsv'
V1TAGS = [('1p_fhc5_thetap', r'$\theta_p$', 'FHC'), ('1p_rhcfull_thetap', '', 'RHC'), ('1p_comb_thetap', '', 'combined'),
          ('1p_fhc5_thpipr', r'$\theta_{\pi p}$', 'FHC'), ('1p_rhcfull_thpipr', '', 'RHC'), ('1p_comb_thpipr', '', 'combined'),
          ('1p_comb_thetap_dpt_2d', r'$\theta_p\times\delta p_T$', 'combined')]
v1 = {}
if os.path.exists(V1):
    import csv
    v1 = {r['extraction']: r for r in csv.DictReader((l for l in open(V1) if not l.startswith('#')), delimiter='\t')}
OLD = [('1p_fhc5_Whad', r'$W_{\rm had}$ (2 regions)', 'FHC'), ('1p_fhc5_dpt2bin', r'$\delta p_T$ (2 bins)', 'FHC'),
       ('1p_comb_pn2bin', r'$p_n$ (2 bins)', 'combined')]
nmem = {rowvals(res[t])[-1] for t, _, _ in OLD if t in res} | {rowvals(v1[t])[-1] for t, _, _ in V1TAGS if t in v1}
L = [r'% generated by report/tools/ensemble_tables_1p.py -- do not edit',
     r'\begin{table}[H]', r'  \centering',
     r'  \caption{Proton-tagged pseudo-data ensembles, ' + ('$100$ members each' if nmem == {100} else
                                                             '$' + '$--$'.join(str(x) for x in sorted(nmem)) + '$ members') + '. Pulls of',
     r"    the unfolded bins against the central-value truth smeared by each member's own $A_C$, in units of",
     r'    the statistical uncertainty (mean, width, fraction within $1\sigma$ and $1.96\sigma$) and of the full',
     r'    framework uncertainty without the MCS term (width), the offset of the ensemble-mean integral from the reference integral (in',
     r'    brackets: in standard errors of the mean) and the member-to-member spread of the integral.',
     r'    Expected: mean $0$, width $1$, coverage $68\%$ and $95\%$',
     r'    (\texttt{data\_release/ensemble\_1p\_2026-09-26.tsv}, \texttt{ensemble\_v1\_2026-09-28.tsv}).}',
     r'  \label{tab:pt_ensemble}', r'  \small', r'  \begin{tabular}{llccccccc}', r'    \toprule',
     r'    & & \multicolumn{4}{c}{statistical} & full & \multicolumn{2}{c}{integral} \\',
     r'    \cmidrule(lr){3-6}\cmidrule(lr){8-9}',
     r'    Extraction & Config. & mean & width & $68\%$ & $95\%$ & width & offset & spread \\', r'    \midrule',
     r'    \multicolumn{9}{l}{\emph{\statValidation{}s}} \\']
L += [row(l, c, res[t]) for t, l, c in OLD if t in res]
if v1:
    L += [r'    \midrule', r'    \multicolumn{9}{l}{\emph{\statSecondaryPl}} \\']
    L += [row(l, c, v1[t]) for t, l, c in V1TAGS if t in v1]
L += [r'    \bottomrule', r'  \end{tabular}', r'\end{table}']
os.makedirs(R + 'tables', exist_ok=True)
open(R + 'tables/ensemble_1p.tex', 'w').write('\n'.join(L) + '\n')
print('wrote tables/ensemble_1p.tex')
for tag, _ in TAGS:
    if tag not in res: continue
    r = res[tag]; s = r['statistical only']; f = r['full']
    print(f"{tag:17s} n={r['members']:3d} bins={r['bins']} stat mean {s['mean']:+.2f} width {s['width']:.2f} "
          f"cov {100*s['cov68']:.1f}/{100*s['cov95']:.1f}  full width {f['width']:.2f}  offset {r['offset_pct']:+.2f}% ({r['offset_sigma']:+.1f} sigma, sd {r['sd_pct']:.1f}%)")
