"""ensemble_tables_1p.py -- evaluate the three proton-tagged fake-data ensembles (FHC W_had in two
regions, 2026-09-26; FHC two-bin delta p_T and combined two-bin p_n, 2026-09-24/25; 100 members each,
slurm_ensemble_1p.sbatch) with ensemble_stat_pulls.evaluate, write data_release/ensemble_1p_2026-09-26.tsv and the coverage
table of the proton-tagged note, tables/ensemble_1p.tex. Run slurm/ens_statcov.sh 1p_<cfg> <obs>
first so every member has its DataStats table.

    python3 report/tools/ensemble_tables_1p.py
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
from ensemble_stat_pulls import evaluate
R = os.path.abspath(os.path.join(HERE, '..')) + '/'
TAGS = [('1p_fhc5_Whad', r'$d\sigma/dW_{\rm had}$ (two regions), FHC'),
        ('1p_fhc5_dpt2bin', r'$d\sigma/d\delta p_T$ (two bins), FHC'),
        ('1p_comb_pn2bin', r'$d\sigma/dp_n$ (two bins), combined')]
res = {}
for tag, _ in TAGS:
    try: res[tag] = evaluate(tag, 100, quiet=True)
    except Exception as e: print(tag, 'failed:', e)

with open(R + 'data_release/ensemble_1p_2026-09-26.tsv', 'w') as o:
    o.write('# Proton-tagged fake-data ensembles (corrected FHC Run-1 exposure): Poisson throws of the central-value\n'
            '# prediction of the w/ trees (slurm_ensemble_1p.sbatch), each carried through univmake + UnfolderNuMI; pulls against\n'
            '# the fixed central-value truth smeared by each member\'s own A_C. Statistical reference = DataStats covariance of the\n'
            '# member; full = total covariance. Offsets are of the ensemble-mean integral from the reference integral.\n')
    o.write('extraction\tmembers\tbins\tpull_mean_stat\tpull_width_stat\tcov68_stat\tcov95_stat\tpull_mean_full\tpull_width_full'
            '\tcov68_full\tcov95_full\tmean_integral\treference_integral\toffset_pct\toffset_sigma_of_mean\tthrow_to_throw_sd_pct\n')
    for tag, _ in TAGS:
        if tag not in res: continue
        r = res[tag]; s = r['statistical only']; f = r['full']
        o.write(f"{tag}\t{r['members']}\t{r['bins']}\t{s['mean']:.2f}\t{s['width']:.2f}\t{100*s['cov68']:.1f}\t{100*s['cov95']:.1f}"
                f"\t{f['mean']:.2f}\t{f['width']:.2f}\t{100*f['cov68']:.1f}\t{100*f['cov95']:.1f}\t{r['mean_integral']:.4f}"
                f"\t{r['reference_integral']:.4f}\t{r['offset_pct']:.2f}\t{r['offset_sigma']:.1f}\t{r['sd_pct']:.1f}\n")
print('wrote data_release/ensemble_1p_2026-09-26.tsv')

def sg(v, d=2):
    t = f"{v:+.{d}f}"; return t[1:] if float(t) == 0 else t      # no signed zero
def row(tag, lab, key):
    r = res[tag][key]
    return f"    {lab} & ${sg(r['mean'])}$ & ${r['width']:.2f}$ & ${100*r['cov68']:.1f}\\%$ / ${100*r['cov95']:.1f}\\%$ \\\\"
def orow(tag, lab):
    r = res[tag]
    return f"    {lab} & ${sg(r['offset_pct'])}\\%$ & ${sg(r['offset_sigma'], 1)}$ & ${r['sd_pct']:.1f}\\%$ \\\\"
L = [r'% generated by report/tools/ensemble_tables_1p.py -- do not edit',
     r'\begin{table}[H]', r'  \centering',
     r'  \caption{Proton-tagged fake-data ensembles, $100$ members each. Upper block: per-bin pulls of the',
     r"    unfolded result against the central-value truth smeared by each member's own $A_C$, in units of",
     r'    the statistical and of the full uncertainty. Lower block: offset of the ensemble-mean integral from',
     r'    the reference integral, in per cent and in units of the standard error of the mean, and the',
     r'    member-to-member spread of the integral (\texttt{data\_release/ensemble\_1p\_2026-09-26.tsv}).}',
     r'  \label{tab:pt_ensemble}', r'  \small', r'  \begin{tabular}{lccc}', r'    \toprule',
     r'    Reference covariance & pull mean & pull width & 68\% / 95\% coverage \\', r'    \midrule',
     r'    \multicolumn{4}{l}{\emph{statistical only}} \\']
L += [row(t, l, 'statistical only') for t, l in TAGS if t in res]
L += [r'    \midrule', r'    \multicolumn{4}{l}{\emph{full}} \\']
L += [row(t, l, 'full') for t, l in TAGS if t in res]
L += [r'    \midrule', r'    expected & $0$ & $1$ & $68\%$ / $95\%$ \\', r'    \midrule',
      r'    Integral & offset & offset$/\sigma_{\rm mean}$ & member spread \\', r'    \midrule']
L += [orow(t, l) for t, l in TAGS if t in res]
L += [r'    \bottomrule', r'  \end{tabular}', r'\end{table}']
os.makedirs(R + 'tables', exist_ok=True)
open(R + 'tables/ensemble_1p.tex', 'w').write('\n'.join(L) + '\n')
print('wrote tables/ensemble_1p.tex')
for tag, _ in TAGS:
    if tag not in res: continue
    r = res[tag]; s = r['statistical only']; f = r['full']
    print(f"{tag:17s} n={r['members']:3d} bins={r['bins']} stat mean {s['mean']:+.2f} width {s['width']:.2f} "
          f"cov {100*s['cov68']:.1f}/{100*s['cov95']:.1f}  full width {f['width']:.2f}  offset {r['offset_pct']:+.2f}% ({r['offset_sigma']:+.1f} sigma, sd {r['sd_pct']:.1f}%)")
