"""infocontent.py -- how much unsmeared shape information each primary result carries.

The unfolded points are the Wiener-SVD estimator A_C x_true, and A_C row sums well below one mean
that much of a reported distribution is set by the regularisation rather than by the data. This
puts the numbers a reader needs beside each primary observable: bins, the smallest migration
diagonal, the range of the A_C row sums, the conditioning s_min/s_1, and the bin-averaged total
uncertainty. Written for FHC (the reference configuration); RHC and combined are in the release.
    python3 report/tools/infocontent.py
"""
import os, sys, numpy as np
HERE=os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
from binning_eval_c50 import side
LIVE='/data/uboone/processed'
# smallest column-normalised migration diagonal (FHC), from the binning re-check table of the
# technical supplement; p_pi is the two-region scheme (91% / 76%)
DIAG={'pmu':0.33,'ppi2bin':0.76,'costhmu':0.68,'thetamu':0.67,'costhpi':0.74,'thmupi':0.79}
UNC ={'pmu':43.5,'ppi2bin':53.9,'costhmu':44.9,'thetamu':32.4,'costhpi':41.0,'thmupi':37.5}
LAB ={'pmu':r'$p_\mu$','ppi2bin':r'$p_\pi$ (two regions)','costhmu':r'$\cos\theta_\mu$',
      'thetamu':r'$\theta_\mu$','costhpi':r'$\cos\theta_\pi$','thmupi':r'$\theta_{\mu\pi}$'}
rows=[]
for o in ['pmu','ppi2bin','costhmu','thetamu','costhpi','thmupi']:
    nb, ac, cond, rel, clo = side(f'{LIVE}/closure_hists_xsec_FHC5_{o}.root')
    rows.append((LAB[o], nb, DIAG[o], min(ac), max(ac), cond, UNC[o]))
out=[r'% generated by report/tools/infocontent.py -- do not edit',
 r'\begin{table}[H]', r'  \centering',
 r'  \caption{Information content of the primary FHC results. The reported points are the',
 r'    Wiener-SVD estimator $A_C\,x_{\rm true}$, not an unsmeared estimate of $x_{\rm true}$; an $A_C$',
 r'    row sum well below one means that bin is set largely by the regularisation. $s_{\min}/s_1$ is',
 r'    the conditioning of $A_C$; the uncertainty is the bin-averaged total including data',
 r'    statistics. Migration diagonals are the smallest over bins.}',
 r'  \label{tab:infocontent}', r'  \small', r'  \begin{tabular}{lccccc}', r'    \toprule',
 r'    Observable & bins & min.\ diagonal & $A_C$ row sums & $s_{\min}/s_1$ & unc.\ [\%] \\', r'    \midrule']
for lab,nb,d,lo,hi,c,u in rows:
    out.append(f'    {lab} & {nb} & ${d:.2f}$ & ${lo:.2f}$--${hi:.2f}$ & ${c:.3f}$ & ${u:.1f}$ \\\\')
out+=[r'    \bottomrule', r'  \end{tabular}', r'\end{table}']
os.makedirs(os.path.join(HERE,'..','tables'),exist_ok=True)
open(os.path.join(HERE,'..','tables','infocontent.tex'),'w').write('\n'.join(out)+'\n')
for r in rows: print('%-28s %d  diag %.2f  A_C %.2f-%.2f  cond %.3f' % r[:6])
