"""infocontent.py -- how much unsmeared shape information each primary result carries.

The unfolded points are the Wiener-SVD estimator A_C x_true, and A_C row sums well below one mean
that much of a reported distribution is set by the regularisation rather than by the data. This
puts the numbers a reader needs beside each primary observable: bins, the smallest migration
diagonal, the range of the A_C row sums, the degrees of freedom for signal and the bin-averaged
total uncertainty. Written for FHC (the reference configuration); RHC and combined are in the release.

Since 2026-09-26 (binning review, supplement sec:binreview) the information measure is the trace of
A_C, the sum of the Wiener filter factors (A_C is similar to the diagonal matrix of those factors,
so its eigenvalues are the factors and its trace their sum), with the number of factors of at least
0.5, the components measured with signal-to-noise of at least one. The conditioning s_min/s_1 used
before only sees the weakest component. The diagonals are read from the unfolder's [DIAGDUMP].
    python3 report/tools/infocontent.py
"""
import os, sys, numpy as np, uproot
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
from binning_eval_c50 import side
LIVE = '/data/uboone/processed'
LOG = '/home/t2k/nowak/MicroBooNE/working_xsec_analyzer/logs/fdfix'
DUMP = '/home/t2k/nowak/MicroBooNE/working_xsec_analyzer/logs/systdump'
OBS = ['pmu', 'ppi3bin', 'costhmu', 'costhpi', 'thmupi']
LOGKEY = {'ppi3bin': 'ppi'}          # unfolder logs and dumps are keyed by the observable, not the binning
LAB = {'pmu': r'$p_\mu$', 'ppi3bin': r'$p_\pi$ (three regions)', 'costhmu': r'$\cos\theta_\mu$',
       'costhpi': r'$\cos\theta_\pi$', 'thmupi': r'$\theta_{\mu\pi}$'}


def min_diag(o):
    for line in open(f"{LOG}/fhc5_{LOGKEY.get(o, o)}.raw"):
        if '[DIAGDUMP]' in line: return min(float(x) for x in line.split(':')[-1].split())
    raise KeyError(o)


def total(o):
    # bin-averaged total uncertainty including data statistics: the "Total (incl. data stat)" row of tab:systbreak
    for line in open(f"{DUMP}/fhc5_{LOGKEY.get(o, o)}.dump"):
        p = line.split()
        if len(p) == 3 and p[0] == '[SYSTDUMP]' and p[1] == 'total': return float(p[2])
    raise KeyError(o)


rows = []
for o in OBS:
    f = f'{LIVE}/closure_hists_xsec_FHC5_{o}.root'
    nb, ac, cond, rel, clo = side(f)
    A = uproot.open(f)['h_A_C'].values().T                  # A_C[i][j]
    W = np.sort(np.linalg.eigvals(A).real)[::-1]            # Wiener filter factors
    rows.append((LAB[o], nb, min_diag(o), min(ac), max(ac), float(np.trace(A)), int((W >= 0.5).sum()), total(o)))

out = [r'% generated by report/tools/infocontent.py -- do not edit',
       r'\begin{table}[H]', r'  \centering',
       r'  \caption{Information content of the primary FHC results. The reported points are the',
       r'    Wiener-SVD estimator $A_C\,x_{\rm true}$, not an unsmeared estimate of $x_{\rm true}$; an $A_C$',
       r'    row sum well below one means that bin is set largely by the regularisation. The trace of $A_C$',
       r'    is the number of degrees of freedom the data determine, and the next column the number of',
       r'    components measured with signal-to-noise of at least one (Wiener filter factors $\geq0.5$);',
       r'    the uncertainty is the bin-averaged total including data statistics. Migration diagonals',
       r'    are the smallest over bins.}',
       r'  \label{tab:infocontent}', r'  \small', r'  \begin{tabular}{lcccccc}', r'    \toprule',
       r'    Observable & bins & min.\ diagonal & $A_C$ row sums & trace $A_C$ & factors $\geq0.5$ & unc.\ [\%] \\',
       r'    \midrule']
for lab, nb, d, lo, hi, tr, n50, u in rows:
    out.append(f'    {lab} & {nb} & ${d:.2f}$ & ${lo:.2f}$--${hi:.2f}$ & ${tr:.2f}$ & {n50} & ${u:.1f}$ \\\\')
out += [r'    \bottomrule', r'  \end{tabular}', r'\end{table}']
os.makedirs(os.path.join(HERE, '..', 'tables'), exist_ok=True)
open(os.path.join(HERE, '..', 'tables', 'infocontent.tex'), 'w').write('\n'.join(out) + '\n')
for r in rows: print('%-32s %d  diag %.2f  A_C %.2f-%.2f  trace %.2f  n50 %d  unc %.1f' % r)
