"""inventory.py -- the result-status tables of the analysis notes, generated from report/status.tsv, the
single source of the status of every product (decision of 2026-09-27).

Writes
  report/tables/inventory.tex   tab:inventory  -- inclusive products (analysis note, technical supplement)
  report/tables/pt_status.tex   tab:pt_status  -- proton-tagged products (proton-tagged note, supplement)
Each row gives the product, whether it is reported in the FHC, RHC and combined configurations, its status in
the four-label vocabulary of shared/status_vocab.tex, and the prerequisites of shared/prerequisites.tex that
block it. The released extractions behind each row are checked to exist in data_release/.
    python3 report/tools/inventory.py [--allow-missing]   (the flag only while a release file is being produced)
"""
import os, csv, glob, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REP = os.path.dirname(HERE)
REL = os.path.join(REP, 'data_release')
MACRO = {'primary': r'\statPrimary', 'secondary': r'\statSecondary', 'validation': r'\statValidation',
         'notreported': r'\statNotReported'}
CFGS = ('FHC5', 'RHCFULL', 'COMB')


def rows():
    lines = [l for l in open(os.path.join(REP, 'status.tsv')) if l.strip() and not l.startswith('#')]
    return list(csv.DictReader(lines, delimiter='\t'))


def check_released(r):
    """Every observable of a reported row must be in the release for each configuration marked Y."""
    missing = []
    if r['observables'] in ('-', 'total'):
        return missing
    for key in r['observables'].split(','):
        for cfg, col in zip(CFGS, ('FHC', 'RHC', 'COMB')):
            if r[col] != 'Y':
                continue
            tag = f"{r['family']}_{cfg}_{key}"
            for p in (f'curves_{tag}.tsv', f'A_C_{tag}.tsv', f'cov/{tag}/cov_total_plusMCS.txt'):
                if not os.path.exists(os.path.join(REL, p)):
                    missing.append(p)
    return missing


def table(fam, label, caption):
    yn = lambda v: 'yes' if v == 'Y' else 'no'
    out = [r'% generated by report/tools/inventory.py from report/status.tsv -- do not edit',
           r'{\footnotesize\setlength{\tabcolsep}{4pt}',
           r'\begin{longtable}{@{}p{6.1cm}ccc p{3.3cm} p{2.2cm}@{}}',
           r'\caption{' + caption + '}', rf'\label{{{label}}}\\',
           r'\toprule', r'Product & FHC & RHC & Comb. & Status & Prerequisites \\', r'\midrule', r'\endfirsthead',
           r'\toprule', r'Product & FHC & RHC & Comb. & Status & Prerequisites \\', r'\midrule', r'\endhead',
           r'\bottomrule', r'\endfoot']
    missing = []
    for r in rows():
        if r['family'] != fam:
            continue
        missing += check_released(r)
        rep = r['status'] != 'notreported'
        cells = [yn(r['FHC']), yn(r['RHC']), yn(r['COMB'])] if rep else ['', '', '']
        pre = r['prerequisites'] if r['prerequisites'] != '-' else ''
        out.append(f"{r['product']} & {' & '.join(cells)} & {MACRO[r['status']]} & {pre} \\\\")
    out += [r'\end{longtable}}']
    if missing and '--allow-missing' not in sys.argv:
        raise SystemExit(f'status.tsv lists products absent from the release: {missing}')
    if missing: print('WARNING (--allow-missing): absent from the release:', missing)
    return '\n'.join(out) + '\n'


def main():
    open(os.path.join(REP, 'tables', 'inventory.tex'), 'w').write(table(
        'incl', 'tab:inventory',
        r'Status of the inclusive products, generated from \texttt{report/status.tsv}. ``yes'' marks the '
        r'configurations in which a product is reported under its status; the prerequisites are those of '
        r'Table~\ref{tab:prerequisites}. The proton-tagged products have their own status table.'))
    open(os.path.join(REP, 'tables', 'pt_status.tex'), 'w').write(table(
        '1p', 'tab:pt_status',
        r'Status of every proton-tagged product, generated from \texttt{report/status.tsv}. ``yes'' marks the '
        r'configurations in which a product is reported under its status; the prerequisites are those of '
        r'Table~\ref{tab:prerequisites}.'))
    n = {s: sum(1 for r in rows() if r['status'] == s) for s in MACRO}
    print('status rows:', n)
    print('wrote tables/inventory.tex and tables/pt_status.tex')


if __name__ == '__main__':
    main()
