"""inventory.py -- the result inventory of the analysis note, generated from the release itself.

The note used to state its own totals in prose ("fifty-one extractions", "eleven observables",
"ten released proton-tagged observables") and those counts drifted apart from each other and from
the release as observables were added and withdrawn. This builds the inventory table from
report/data_release/index_extractions.tsv and total_xsec.tsv, plus the extractions that exist but
are not in that release directory yet, so the note cannot disagree with what was actually produced.

Writes report/tables/inventory.tex (analysis note) and inventory_1p.tex (proton-tagged note).
    python3 report/tools/inventory.py
"""
import os, csv, collections

HERE = os.path.dirname(os.path.abspath(__file__))
REP = os.path.dirname(HERE)
REL = os.path.join(REP, 'data_release')
OUT = os.path.join(REP, 'tables', 'inventory.tex')
CFG = ('FHC5', 'RHCFULL', 'COMB')

# extractions that exist but post-date the release directory; kept here explicitly so the table
# says so rather than silently omitting them.
EXTRA = [
    ('Proton-tagged angular ($\\theta_p$, $\\theta_{\\pi p}$)', 2, 3, 6,
     'proposed secondary', 'not in the release directory'),
    ('Two-dimensional pairs', 8, 3, 24, 'two proposed, combined only',
     'not in the release directory'),
]


def rows():
    p = os.path.join(REL, 'index_extractions.tsv')
    out = []
    with open(p) as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            fields = line.rstrip('\n').split('\t')
            if fields[0] == 'tag':
                continue
            out.append(fields)
    return out


def main():
    r = rows()
    fam = collections.Counter(x[1] for x in r)
    obs = {k: sorted({x[3] for x in r if x[1] == k}) for k in fam}
    wd = [x for x in r if x[-1].startswith('withdrawn')]
    ntot = sum(1 for l in open(os.path.join(REL, 'total_xsec.tsv'))
               if l.strip() and not l.startswith('#') and not l.startswith('family'))

    n_incl = len(obs.get('incl', []))
    n_1p = len(obs.get('1p', []))
    head = [r'% generated by report/tools/inventory.py -- do not edit', r'\begin{table}[H]', r'  \centering']
    tab = [r'  \small', r'  \begin{tabular}{lccl}', r'    \toprule',
           r'    Family & Observables & Extractions & Status \\', r'    \midrule']
    # 2026-09-27: one table per note; the analysis note lists the inclusive family only
    lines = head + [
        '  \\caption{Extractions of the inclusive analysis, generated from the result index '
        '(\\texttt{report/tools/inventory.py}), one per observable and configuration. The proton-tagged '
        'extractions are listed in the companion note.}',
        r'  \label{tab:inventory}'] + tab + [
        r'    Differential & %d & %d & primary \\' % (n_incl, fam.get('incl', 0)),
        r'    One-bin total & 1 & 3 & primary \\',
        r'    \midrule',
        r'    \multicolumn{4}{l}{\emph{Examined, not reported (Appendix~\ref{app:withdrawn})}} \\',
        r'    Five-bin $d\sigma/dp_\pi$ & 1 & n/a & not reported \\',
        r'    $d\sigma/d\theta_\mu$ & 1 & n/a & not reported \\',
        r'    \bottomrule', r'  \end{tabular}', r'\end{table}']
    lines1p = head + [
        '  \\caption{Extractions of the proton-tagged analysis, generated from the result index '
        '(\\texttt{report/tools/inventory.py}), one per observable and configuration.}',
        r'  \label{tab:pt_inventory}'] + tab + [
        r'    Differential & %d & %d & secondary \\' % (n_1p, fam.get('1p', 0)),
        r'    One-bin total & 1 & 3 & secondary \\']
    for name, nobs, _ncfg, nextr, status, _note in EXTRA:
        lines1p.append(r'    %s & %d & %d & %s$^{1}$ \\' % (name.replace('Proton-tagged angular', 'Proton angles'), nobs, nextr, status))
    lines1p += [r'    \midrule',
                r'    \multicolumn{4}{l}{\emph{Of the above, not reported (\S\ref{sec:pt_wpip_withdrawn})}} \\',
                r'    Differential $W_{\pi p}$ & 1 & %d & not reported \\' % len({x[2] for x in wd}),
                r'    \bottomrule', r'  \end{tabular}',
                r'  \par\smallskip\noindent{\footnotesize $^{1}$ Extracted separately from the indexed '
                r'result set and not listed in its index.}',
                r'\end{table}']
    open(os.path.join(REP, 'tables', 'inventory_1p.tex'), 'w').write('\n'.join(lines1p) + '\n')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w').write('\n'.join(lines) + '\n')
    print(f'inclusive: {n_incl} observables, {fam.get("incl", 0)} extractions')
    print(f'proton-tagged: {n_1p} observables, {fam.get("1p", 0)} extractions')
    print(f'released differential extractions: {len(r)}   one-bin totals: {ntot}')
    print(f'withdrawn differential rows: {len(wd)}')
    print('wrote', OUT)


if __name__ == '__main__':
    main()
